config/routes.rb
BetterEducation::Application.routes.draw do

  root 'home#index'

  devise_for :users

  resources :colleges

  get "/results", to: "pages#results", as: :results

end

app/models/award.rb
class Award
  include Mongoid::Document
  include Mongoid::Timestamps

  field :award 
  field :category

  belongs_to :college

  CATEGORIES = ["academic", "athletic", "social"]
end

app/models/college.rb
class College
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :name
  slug :name
  field :partial

  # University website links
  field :website
  field :athletics_website

  #about
  field :description
  field :mascot
  field :conference_id

  # Geography
  field :city
  field :state_id

  # Social
  field :facebook
  field :twitter
  field :youtube
  field :flickr

  # Booleans
  field :paid,    type: Boolean,    default: false
  field :custom,  type: Boolean,    default: false
  field :live,    type: Boolean,    default: false

  # Styles
  field :background_color,  default: "#fff"
  field :headings_color,    default: "#000"
  field :logo

  belongs_to :conference,     index: true
  belongs_to :state,          index: true

  has_many :college_sports,   dependent: :destroy
  has_many :links,            dependent: :destroy
  has_many :tuitions,         dependent: :destroy
  has_many :awards,           dependent: :destroy

  has_and_belongs_to_many :majors, inverse_of: :majors

  validates :name,      presence: true
  validates :name,      uniqueness: true
  validates :partial,   uniqueness: true

  scope :custom, -> { where(custom: true) }
  scope :abc, -> { order_by('name ASC') }
  scope :school -> (school) {where(name: school)}
  scope :state, -> (state) { where(state: state) }
  scope :conference, -> (conference) { where(conference: conference) }


  def to_param
    slug
  end

  def self.search(school, state, conference)
    if school.present? || state.present? || conference.present?
      colleges = College.abc
      colleges = colleges.school(school) if school.present?
      colleges = colleges.state(State.where(name: state).first.id) if state.present?
      colleges = colleges.conference(Conference.where(name: conference).first.id) if conference.present?
      colleges
    else
      self.abc
    end

  end
  
end

app/models/college_sport.rb
class CollegeSport
  include Mongoid::Document
  include Mongoid::Timestamps

  field :college_id
  field :sport_id
  field :mens,        type: Boolean
  field :womens,      type: Boolean
  field :division

  belongs_to :college 
  belongs_to :sport
  
end

app/models/conference.rb
class Conference
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :abbreviation

  has_many :colleges

  validates :name, presence: true

  default_scope order_by('name ASC')
end

app/models/link.rb
class Link
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :url
  field :description

  belongs_to :college

  validates :name, :url, presence: true
end

app/models/major.rb
class Major
  include Mongoid::Document
  include Mongoid::Timestamps

  field :major

  has_and_belongs_to_many :colleges, inverse_of: :colleges
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :email
  field :content

  validates :name, :email, :content, presence: true

  validates_format_of :email,
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, 
    message: "is an invalid email"

  after_create :send_email

  private

  def send_email
    Notifier.contact_form(self).deliver
  end
end

app/models/sport.rb
class Sport
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name

  has_many :college_sports, dependent: :destroy

  validates :name, presence: true
end

app/models/state.rb
class State
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name

  validates :name, presence: true
  validates :name, uniqueness: true

  default_scope order_by('name ASC')
end

app/models/tuition.rb
class Tuition
  include Mongoid::Document
  include Mongoid::Timestamps

  field :year, type: Integer
  field :out_of_state
  field :in_state_tuition
  field :college_id

  belongs_to :college 

  validates :year, numericality: true
  validates :year, :out_of_state, :in_state, presence: true

  default_scope order_by('year DESC')
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :first_name
  field :last_name
  field :address
  field :address2
  field :city
  field :state 
  field :postal_code
  field :email              
  field :encrypted_password

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Token authenticatable
  field :authentication_token, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

  layout 'college'

  def show
    @college = College.find params[:id]
    @page_title = "#{@college.name}"
    @partial = @college.partial if @college.partial
    @sports = @college.college_sports.includes(:sport).all
    @links = @college.links.all
    @tuition = @college.tuitions.limit(5)
    @majors = @college.majors.all
    @awards = @college.awards.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @colleges = College.all

    # Temporary testing
    @college_free = College.first
    @college_paid = College.custom.first
  end 

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @page_title = "Contact Us"
    @message = Message.new
  end

  def create
    @message = Message.create param[:message]
    if @message.save
      redirect_to root_path, notice: "Thanks"
    else
      render :new
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def results
    @colleges = College.search(params[:state], params[:conference])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    if @page_title.present?
      @page_title
    else
      "Better Education"
    end
  end

  def partial
    @partial if @partial.present?
  end

end

app/helpers/college_helper.rb
module CollegeHelper

  def division
    @division = 
      [
        ['Division 1'],
        ['Division 2'],
        ['Division 3'],
        ['Junior College']
      ]
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def us_states
  	State.all.map(&:name)
  end

  def colleges
    College.all.map(&:name)
  end

  def conferences
    Conference.all.map do |conference|
      if conference.abbreviation
        "#{conference.name} (#{conference.abbreviation})"
      else
        conference.name
      end
    end
  end
end

app/views/colleges/_awards.html.haml
- @awards.each do |award|
  = award.award

app/views/colleges/_navigation.html.haml
#college-navigation-bar
  %ul
    %li Home
    %li Sports
    %li Tuition

app/views/colleges/_social.html.haml
%ul#social
  -if @college.facebook.present?
    %li= link_to "@college.facebook", "#"
  -if @college.twitter.present?
    %li= link_to "@college.twitter", "#"
  -if @college.youtube.present?
    %li= link_to "@college.youtube", "#"
  -if @college.flickr.present?
    %li= link_to "@college.flickr", "#"

app/views/colleges/_sports.html.haml
%table
  %thead
    %tr
      %th Sport
      %th Men's
      %th Women's
  %tbody
    - @sports.each do |sport|
      %tr
        %td= sport.sport.name
        %td= sport.mens
        %td= sport.womens

app/views/colleges/_tuition.html.haml
- @tuition.each do |tuition|
  = tuition.in_state
  = tuition.out_of_state

app/views/colleges/partials/_michigan_state_university.html.haml
.container
  %h1= @college.name

app/views/colleges/show.html.haml
- if @college.custom
  = render "colleges/partials/#{@partial}"
- else
  :sass
    body
      background-color: #{@college.background_color}

    h1, h2, h3, h4, h5
      color: #{@college.headings_color}

    
      
  .container#page
    .row
      .col-lg-12
        %h1= @college.name
        = image_tag('header-break.png')
        %p
          = @college.website
          = @college.city
          = @college.state.name
          = @college.mascot
          = @college.conference.name

        %p
          = render 'social'

    .row
      .col-lg-12
        = render 'navigation'

    .row
      .col-lg-6
        %h1 Location
        #map

    

    .row
      .col-lg-12
        %h3 Sample Text
        %p
          Bacon ipsum dolor sit amet strip steak short loin short ribs ham, pork kielbasa ground round. Short ribs sausage ball tip pig chuck. Pork loin shankle short loin t-bone, chuck drumstick kevin chicken sirloin turducken cow tongue bacon filet mignon boudin. Biltong turducken pork loin, chuck ball tip boudin ground round brisket spare ribs t-bone pancetta kielbasa tenderloin chicken strip steak. Andouille sirloin chuck, tongue turducken tenderloin salami strip steak short loin rump. Chicken ground round leberkas pancetta andouille shank biltong, short loin beef pork loin fatback beef ribs ribeye shankle.

    .row
      %h2 Tuition
      = render 'tuition'

    .row
      %h2 Sports
      = render 'sports'

    .row
      .col-lg-12
        %h2 Awards
        = render 'awards'

    .row
      %h2 Links
      = render 'links'

  :coffee
    $("#map").goMap
      zoom: 12
      maptype: "ROADMAP"
      address: "#{@college.name}"

    $.goMap.createMarker address: "#{@college.name}"

app/views/home/index.html.haml
%h1 Welcome to Better Education

= form_tag results_path, method: :get do
  = select_tag :college, options_for_select(colleges), include_blank: true
  = select_tag :state, options_for_select(us_states), include_blank: true
  = select_tag :conference, options_for_select(conferences), include_blank: true
  = submit_tag 'search', class: 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .row
      .col-lg-12
        .nav
          #logo.pull-left
            = link_to "Better Education", root_path
          .pull-right
            = render 'shared/navigation'
      .container#content
        = yield

      .footer
        .row
          .col-lg-12
            = render 'shared/footer'

app/views/layouts/college.html.haml
!!!
%html
  %head
    %title= page_title
    %script{src: "http://maps.google.com/maps/api/js?sensor=false"}
    = stylesheet_link_tag    "application"
    = stylesheet_link_tag   "partials/#{partial}" if @college.custom
    = javascript_include_tag "application"
    = javascript_include_tag "partials/#{partial}" if @college.custom
    = csrf_meta_tags

  %body
    = yield

app/views/pages/_college_results.html.haml
- @colleges.each do |college|

  %p
    = link_to college.name, college
    = college.mascot
    = college.city
    = college.state.name
    = college.conference.name

app/views/pages/_search_sidebar.html.haml
%h2 Search

= form_tag results_path, method: :get do

  = select_tag :college, options_for_select(colleges), include_blank: true
  = select_tag :state, options_for_select(us_states), include_blank: true
  = select_tag :conference, options_for_select(conferences), include_blank: true
  = submit_tag 'search', class: 'btn'

app/views/pages/results.html.haml
.row
  .col-lg-2
    = render 'search_sidebar'

  .col-lg-10

    %h1 Search Results

    = render 'college_results'

app/views/shared/_footer.html.haml
I like feet

app/views/shared/_navigation.html.haml
- if current_user
  Hello
- else
  = link_to "Sign in", new_user_session_path
  = link_to "Sign up", new_user_registration_path